# Site settings
title: Acupuncture by Jewels
email-user: jewels
email-domain: kirasretreats.com
description: Jewels' personal acupuncture site
author: Spencer Scorcelletti
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acubyjewels.com" # the base hostname & protocol for your site
twitter_username: TBD
github_username:  TBD
defaults:
  - scope:
      path: ""      # currently, this appears to break unless you specify empty quotes...
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      default-styles:
      - { src: /css/vendor.css }
      - { src: /css/agency.css }
      - { src: /css/post.css }
      default-scripts:
      - { src: /scripts/jquery.min.js }
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      default-styles:
      - { src: /css/vendor.css }
      - { src: /css/agency.css }
      default-scripts:
      - { src: /scripts/jquery.min.js }
      - { src: /scripts/bootstrap.min.js }
      - { src: /scripts/jquery.easing.min.js }
      - { src: /scripts/classie.js }
      - { src: /scripts/cbpAnimatedHeader.js }
      - { src: /scripts/agency.js }

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

sass:
  style: compressed

collections:
  - content
